# Generated by Django 3.0.2 on 2020-03-02 07:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField()),
                ('choose', models.CharField(blank=True, choices=[('E', 'Email'), ('P', 'Phone Number'), ('D', 'Direct Booking')], default='e', help_text='Room Status', max_length=1)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserverd_room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('e', 'Empty'), ('o', 'occupied')], default='e', help_text='Room Status', max_length=1)),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Occupied_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.Reservation')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Hosted_at',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.Guest')),
                ('occupied_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.Occupied_room')),
            ],
        ),
    ]
