# Generated by Django 3.0.2 on 2020-03-16 13:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reserverd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.Reserverd_room')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.Room')),
            ],
        ),
    ]
